name: docs
channels:

  - conda-forge
  - pytorch
  - defaults

dependencies:

  # Base depends
  - python >=3.8,<=3.10
  - pip

  # Core dependencies
  - numpy
  - pandas
  - pytorch<=2.2.0 # latest version does not define name '_accumulate' from 'torch._utils'
  - pydantic<2    # workaround to avoid clashes with lightning
  - lightning

  # utils
  - matplotlib
  - nbsphinx
  - ipython
  - ipykernel
  - scipy<1.11    # latest version does not work with kdepy

  # Pip-only installs
  - pip:
    - sphinx-copybutton
    - furo
    - KDEpy

